CREATE VIEW wd_only_Marksmanship_Bonus AS
SELECT wd_EID, JOB_PROFILE, DEPARTMENT_NBR, DEPARTMENT_TITLE, LEGACY_STATUS, wd_PAY_LEVEL, wd_BONUS_CODE
FROM hrp_al_wd_paysr_bonus_analysis
WHERE wd_EID IS NOT NULL
  AND JOB_PROFILE IS NOT NULL
  AND DEPARTMENT_NBR IS NOT NULL
  AND DEPARTMENT_TITLE IS NOT NULL
  AND LEGACY_STATUS IS NOT NULL
  AND wd_PAY_LEVEL IS NOT NULL
  AND wd_BONUS_CODE = 'Marksman';
  
select * from wd_only_Marksmanship_Bonus;